### ISSUE TITLE
additional materials, text notes

### ISSUE THREAD

**Issue by bnawras** [bogdan-lab/CppBlackBelt#1]
Hi, I watched the video lectures, but I remember that there were some additional materials, text notes. I would appreciate it if you would share them. Because now this course is available only for old students. I'm interested in black belt.

**Comment by bogdan-lab** [comment]
![image](https://user-images.githubusercontent.com/60753036/232197566-5f1c5a4d-e819-46c2-9aa7-b2a24018b924.png)
No, materials are not available for me too.
